#!/bin/sh
if [ -f /usr/bin/w3m ]; then
    BROWSER=w3m
elif [ -f /usr/bin/lynx ]; then
    BROWSER=lynx
elif [ -f /usr/bin/elinks ]; then
    BROWSER=elinks
elif [ -f /usr/bin/links ]; then
    BROWSER=links
elif [ -f /usr/bin/links2 ]; then
    BROWSER=links2
fi

if [ -z "$1" ]; then
   echo "Add a two-digit number, like 'slartie 03'"
else
   URL=http://slartie.com/issues/
   ISS=issue_00$1
   TXT=newsletter-issue-00$1
   ADR=$URL$TXT
   $BROWSER $ADR
fi


